### ISSUE TITLE
specification of negative numeric literal values

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Docs#4]
The specification of numeric literal values in the grammar does not explicitly state that an optional minus sign can appear before the integer part.  Although this can be implemented later as a unary minus expression,  it seems more appropriate to support a signed numeric data type.

**Comment by gyenesvi** [comment]
This is currently treated differently by the flat/compositional parsers, and needs to be clarified in the spec/grammar.
* In the flat case, there are no unary expressions, the numeric literal might contain a minus sign (needed to be able to describe negative numbers).
* In the compositional case, there is a need for a unary minus operator (for expressions like `-x`) and therefore the minus sign before a number will also be interpreted as a unary minus operator, hence negative numbers are not needed.

I could not find a unified solution that works for both. Alternatively, we can just enable negative numbers in the compositional case too, although they will never be interpreted as such by the parser.

**Comment by jnorwood** [comment]
Ok, so  you are saying it will be necessary to specify negative literal values in the flat case, since there are no expression operations for the flat parsing (specifically no unary minus).

For the compositional case:
-   1  and -1 could both be handled by unary minus
I suppose just disable the negative literal in the grammar for compositional case would be best.
 
Is there a use case that requires a unary + arithmetic operator?

**Comment by gyenesvi** [comment]
Yes, the flat case needs the negative literals, and it could be disabled in the compositional case.

I don't know of any use cases that explicitly require the unary + operator.

**Comment by gyenesvi** [comment]
This has been fixed in the final version of the spec.

**Comment by jnorwood** [comment]
Ok, thanks.   The spec expanation that minus is not allowed is a little confusing.
The unary minus is still allowed, but is handled by the expression evaluator instead of as a negative literal value.

**Comment by gyenesvi** [comment]
We could rephrase it as "not allowed as part of the numeric literal". Does that explain it better?

**Comment by jnorwood** [comment]
yes, that's fine.  I'm closing this.
