### ISSUE TITLE
inconsistent use of default values for border parameter

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Docs#5]
It isn't evident to me why some operations require the user to specify a border string value, while others define the default value.  If there is some most commonly used value, shouldn't it be consistently provided as default?

**Comment by gyenesvi** [comment]
Can you specify which ones do not specify default values? Running a search through the spec I see default values for all operations (there are a few upsample examples without default values which are not part of the standard (stated in the spec), and they are actually specializations of `multilinear_upsample`, which does have a default value, `'replicate'`). Furthermore, in almost all cases, the default value is the same, namely `'constant'`.

**Comment by jnorwood** [comment]
Those are the only ones.  I missed the statement about them not being part of the standard.  I'm closing this
