### ISSUE TITLE
Invocation grammar in A.2

### ISSUE THREAD

**Issue by zoeoz** [KhronosGroup/NNEF-Docs#9]
Definition for invocation production in A.2 Compositional Grammar is missing the optional generic type-name specification.

**Comment by zoeoz** [comment]
Also, example code on p. 32 is missing base types in the tensor-type-spec

**Comment by gyenesvi** [comment]
Right, got it, being fixed.

**Comment by gyenesvi** [comment]
Fixed in spec version 1.0.1.
